apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-dissector-data
  labels:
    app: song-dissector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard   # uncomment + edit to pin a specific class
