apiVersion: v1
kind: Service
metadata:
  name: song-dissector
  labels:
    app: song-dissector
spec:
  type: NodePort
  selector:
    app: song-dissector
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30081   
